force-app/main/default/objects/Locations__c/Locations__c.object-meta.xml
<CustomObject>
    <label>AccLocation</label>
    <nameField>
        <label>Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locations__c/fields/Address__c.field-meta.xml
<CustomField>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>123</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/Locations__c/fields/Postalcode__c.field-meta.xml
<CustomField>
        <fullName>Postalcode__c</fullName>
        <label>Postalcode</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/classes/ContactList.cls
public class ContactList {
	@AuraEnabled
    public static List<Contact> getContactList(){
        List<Contact> contactlist=[Select id,name,firstName,lastname,email from contact limit 10];
        return contactlist;
    }
    //New Method
    @AuraEnabled
    public static List<Account> getAccContactList(){
       List<Account> AccountList= [select id,name,(select id,name,Address__c,Postalcode__c from AccLocations__r) from Account where id='0012v00002RkjtZ'];
       //List<Account> AccountList= [select id,name from Account where id='0012v00002RkjtZ'];
       List<AccContactWrapper> acccontwrap=new List<AccContactWrapper>();
        for(Account u: AccountList){
            AccContactWrapper acc=new AccContactWrapper(u.name,u.AccLocations__r);
            //acc.AccountName=u.name;
           // acc.contList=u.AccLocations__r;    		 
        	 acccontwrap.add(acc);
		}
        return AccountList;
    }
    
    public class AccContactWrapper {
        public String AccountName  { get; set; }
        /*public String Location  { get; set; }
        public String zipcode { get; set; }*/
        public List<Locations__c> contList { get; set; }
        public AccContactWrapper(String  AccountName,List<Locations__c> contList ) {
            this.AccountName = AccountName;
            this.contList =contList;
        }
    }
}